# version: '1.0'

services:
  database:
    image: postgres:latest
    container_name: generic_task
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: generic
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
volumes:
  db_data:

